apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: stack-pr-test
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-job-standardization
spec:
  description: >
    PR testing pipeline. Uses the currently running apps in the cluster and only
    builds/replaces the one app being tested (changed-app). Other apps are left
    as-is; Telepresence intercepts route PR traffic only to the new build.
    Tests one app at a time (changed-app is required when invoking this pipeline).
    1. Clones platform repo and resolves the stack graph
    2. Clones and builds ONLY the changed app (snapshot tag) — no build of other apps
    3. Deploys intercepts only for that app; rest of stack keeps running as-is
    4. Validates header propagation, runs test suites
    5. After tests pass: bumps RC version, pushes version commit
    6. Cleans up PR pods (always)
    PR builds use snapshot tagging so they are never confused with real releases.

  params:
    - name: git-url
      description: "Platform repo URL (e.g. tekton-dag) — has stacks/, versions; app repos are cloned separately from stack"
    - name: git-revision
      description: "Branch, tag, or SHA for platform repo and (unless overridden) app repos"
    - name: stack-file
      description: "Path to the stack YAML relative to repo root"
      default: "stacks/stack-one.yaml"
    - name: changed-app
      description: "App being tested (required). Only this app is built and given an intercept; other apps use existing cluster deployments."
      default: ""
    - name: pr-number
      description: "PR number"
    - name: app-revisions
      description: 'Optional JSON map app → revision for cloning app repos (e.g. {"demo-fe":"pr-branch"}). Used when the PR is in the app repo so the changed app is checked out at its PR branch.'
      default: "{}"
    - name: image-registry
      description: "Container registry base (e.g. 123456.dkr.ecr.us-east-1.amazonaws.com)"
    - name: version-overrides
      description: "JSON map of app → version overrides (empty = use versions.yaml)"
      default: "{}"
    - name: compile-image-npm
      description: "Pre-built image for npm compile"
      default: "localhost:5000/tekton-dag-build-node:latest"
    - name: compile-image-maven
      description: "Pre-built image for Maven compile"
      default: "localhost:5000/tekton-dag-build-maven:latest"
    - name: compile-image-gradle
      description: "Pre-built image for Gradle compile"
      default: "localhost:5000/tekton-dag-build-gradle:latest"
    - name: compile-image-pip
      description: "Pre-built image for pip compile"
      default: "localhost:5000/tekton-dag-build-python:latest"
    - name: compile-image-php
      description: "Pre-built image for Composer/PHP compile"
      default: "localhost:5000/tekton-dag-build-php:latest"
    - name: dashboard-url
      description: "Base URL of Tekton Dashboard; PR comment will include link to this run (optional)"
      default: ""
    - name: github-secret-name
      description: "Kubernetes secret name for GitHub token (key: token) when posting PR comments"
      default: "github-token"
    - name: pr-repo-url
      description: "When PR is in the app repo, pass the app repo URL here so the PR comment is posted to the correct repo; empty = use git-url (platform repo)"
      default: ""

  workspaces:
    - name: shared-workspace
      description: "Shared PVC for source code and test data"
    - name: ssh-key
      description: "Volume with SSH key (id_ed25519 or id_rsa) for cloning app repos; required for SSH pull"
    - name: build-cache
      optional: true
      description: "Persistent dependency cache (.m2, .npm, etc.). Create once, reuse across runs."

  results:
    - name: test-summary
      value: $(tasks.run-tests.results.test-summary)

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: resolve-stack
      taskRef:
        name: resolve-stack
      params:
        - name: stack-file
          value: $(params.stack-file)
        - name: changed-app
          value: $(params.changed-app)
        - name: pr-number
          value: $(params.pr-number)
        - name: version-overrides
          value: $(params.version-overrides)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-source

    # Clone each app repo (from stack .apps[].repo) via SSH into workspace/<app-name>
    - name: clone-app-repos
      taskRef:
        name: clone-app-repos
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
        - name: git-revision
          value: $(params.git-revision)
        - name: app-revisions
          value: $(params.app-revisions)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: ssh-key
          workspace: ssh-key
      runAfter:
        - resolve-stack

    # Snapshot tag for PR builds (run name) — not a release version
    - name: pr-snapshot-tag
      taskRef:
        name: pr-snapshot-tag
      params:
        - name: snapshot-tag
          value: $(context.pipelineRun.name)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
      runAfter:
        - resolve-stack

    # Select which tools are needed for build-apps (writes .tool-apps.json)
    - name: build-select-tool-apps
      taskRef:
        name: build-select-tool-apps
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - clone-app-repos
        - pr-snapshot-tag

    # Only the compile step for the app's tool runs (e.g. npm for demo-fe)
    - name: build-compile-npm
      when:
        - input: $(tasks.resolve-stack.results.run-compile-npm)
          operator: in
          values: ["true"]
      taskRef:
        name: build-compile-npm
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: compile-image-npm
          value: $(params.compile-image-npm)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-cache
          workspace: build-cache
      runAfter:
        - build-select-tool-apps

    - name: build-compile-maven
      when:
        - input: $(tasks.resolve-stack.results.run-compile-maven)
          operator: in
          values: ["true"]
      taskRef:
        name: build-compile-maven
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: compile-image-maven
          value: $(params.compile-image-maven)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-cache
          workspace: build-cache
      runAfter:
        - build-select-tool-apps

    - name: build-compile-gradle
      when:
        - input: $(tasks.resolve-stack.results.run-compile-gradle)
          operator: in
          values: ["true"]
      taskRef:
        name: build-compile-gradle
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: compile-image-gradle
          value: $(params.compile-image-gradle)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-cache
          workspace: build-cache
      runAfter:
        - build-select-tool-apps

    - name: build-compile-pip
      when:
        - input: $(tasks.resolve-stack.results.run-compile-pip)
          operator: in
          values: ["true"]
      taskRef:
        name: build-compile-pip
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: compile-image-pip
          value: $(params.compile-image-pip)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-cache
          workspace: build-cache
      runAfter:
        - build-select-tool-apps

    - name: build-compile-composer
      when:
        - input: $(tasks.resolve-stack.results.run-compile-composer)
          operator: in
          values: ["true"]
      taskRef:
        name: build-compile-composer
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: compile-image-php
          value: $(params.compile-image-php)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-cache
          workspace: build-cache
      runAfter:
        - build-select-tool-apps

    # Containerize runs after select + whichever compile task(s) ran
    - name: build-containerize
      taskRef:
        name: build-containerize
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
        - name: image-registry
          value: $(params.image-registry)
        - name: image-tag
          value: $(tasks.pr-snapshot-tag.results.snapshot-versions)
        - name: tag-prefix
          value: ""
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-compile-npm
        - build-compile-maven
        - build-compile-gradle
        - build-compile-pip
        - build-compile-composer

    - name: deploy-intercepts
      taskRef:
        name: deploy-stack-intercepts
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
        - name: propagation-chain
          value: $(tasks.resolve-stack.results.propagation-chain)
        - name: built-images
          value: $(tasks.build-containerize.results.built-images)
        - name: intercept-header-value
          value: $(tasks.resolve-stack.results.intercept-header-value)
      runAfter:
        - build-containerize

    - name: validate-propagation
      taskRef:
        name: validate-stack-propagation
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: propagation-chain
          value: $(tasks.resolve-stack.results.propagation-chain)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
        - name: intercept-header-value
          value: $(tasks.resolve-stack.results.intercept-header-value)
      runAfter:
        - deploy-intercepts

    - name: run-tests
      taskRef:
        name: run-stack-tests
      params:
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)
        - name: app-list
          value: $(tasks.resolve-stack.results.app-list)
        - name: entry-app
          value: $(tasks.resolve-stack.results.entry-app)
        - name: propagation-chain
          value: $(tasks.resolve-stack.results.propagation-chain)
        - name: build-apps
          value: $(tasks.resolve-stack.results.build-apps)
        - name: intercept-header-value
          value: $(tasks.resolve-stack.results.intercept-header-value)
      workspaces:
        - name: test-source
          workspace: shared-workspace
      runAfter:
        - validate-propagation

  finally:
    - name: cleanup
      taskRef:
        name: cleanup-stack-pods
      params:
        - name: deployed-pods
          value: $(tasks.deploy-intercepts.results.deployed-pods)
        - name: stack-json
          value: $(tasks.resolve-stack.results.stack-json)

    - name: post-pr-comment
      taskRef:
        name: post-pr-comment
      params:
        - name: git-url
          value: $(params.git-url)
        - name: pr-repo-url
          value: $(params.pr-repo-url)
        - name: pr-number
          value: $(params.pr-number)
        - name: pipeline-run-name
          value: $(context.pipelineRun.name)
        - name: namespace
          value: $(context.pipelineRun.namespace)
        - name: status
          value: "Completed"
        - name: test-summary
          value: $(tasks.run-tests.results.test-summary)
        - name: dashboard-url
          value: $(params.dashboard-url)
        - name: github-secret-name
          value: $(params.github-secret-name)
