apiVersion: tektondag.io/v1alpha1
kind: StackRun
metadata:
  creationTimestamp: "2026-09-28T03:14:30Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: tekton-job-standardization
    tektondag.io/mode: pr
  name: stackrun-pr-27exw
  namespace: tekton-pipelines
  resourceVersion: "13752"
  uid: ab4b6aed-79b3-4acc-9c08-2afcdb19bce0
spec:
  appRevisions: '{}'
  cacheRepo: ""
  changedApp: demo-fe
  gitRevision: main
  gitUrl: https://github.com/jmjava/tekton-dag.git
  imageRegistry: localhost:5000
  interceptBackend: mirrord
  maxRetries: 2
  mode: pr
  prNumber: 903
  stackFile: stacks/stack-one.yaml
  stackRef: stack-one
  timeout: 2h
status:
  conditions:
  - lastTransitionTime: "2026-09-28T03:14:30Z"
    message: PipelineRun stackrun-pr-27exw phase=Completed
    observedGeneration: 1
    reason: Completed
    status: "False"
    type: Ready
  observedGeneration: 1
  phase: Completed
  pipelineRunName: stackrun-pr-27exw
