apiVersion: tektondag.io/v1alpha1
kind: StackRun
metadata:
  creationTimestamp: "2026-09-28T03:13:08Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: tekton-job-standardization
    tektondag.io/mode: bootstrap
  name: stackrun-bootstrap-bhmj5
  namespace: tekton-pipelines
  resourceVersion: "12224"
  uid: 3e33705f-40f1-4543-9da2-beaec1beedc3
spec:
  cacheRepo: ""
  gitRevision: main
  gitUrl: https://github.com/jmjava/tekton-dag.git
  imageRegistry: localhost:5000
  maxRetries: 2
  mode: bootstrap
  stackFile: stacks/stack-one.yaml
  stackRef: stack-one
  timeout: 2h
status:
  conditions:
  - lastTransitionTime: "2026-09-28T03:13:08Z"
    message: PipelineRun stackrun-bootstrap-bhmj5 phase=Completed
    observedGeneration: 1
    reason: Completed
    status: "False"
    type: Ready
  observedGeneration: 1
  phase: Completed
  pipelineRunName: stackrun-bootstrap-bhmj5
