{{- $script := .Files.Get "raw/scripts/run-stack-tests-runners.sh" -}}
{{- if $script }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: run-stack-tests-runners
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tekton-job-standardization
    {{- include "tekton-dag.labels" . | nindent 4 }}
data:
  run-stack-tests-runners.sh: |
    {{- $script | nindent 4 }}
{{- end }}
