{{- if and .Values.workspaces.buildCache.enabled (default false .Values.workspaces.buildCache.create) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tekton-dag.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.workspaces.buildCache.storageClass }}
  storageClassName: {{ .Values.workspaces.buildCache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspaces.buildCache.size }}
{{- end }}
